# HTML5 tags for picolisp
(load "@lib/xhtml.l")

(de <nav> (Attr . Prg)
  (tag 'nav Attr 2 Prg) )

(de <header> (Attr . Prg)
  (tag 'header Attr 2 Prg) )

(de <footer> (Attr . Prg)
  (tag 'footer Attr 2 Prg) )

(de <article> (Attr . Prg)
  (tag 'article Attr 2 Prg) )

(de <section> (Attr . Prg)
  (tag 'section Attr 2 Prg) )

(de <aside> (Attr . Prg)
  (tag 'aside Attr 2 Prg) )

(de <blockquote> (Attr . Prg)
  (tag 'blockquote Attr 2 Prg) )
